'use client'
import { useState, useEffect } from 'react'
import { useAuth } from '@/lib/useAuth'
import { supabase } from '@/lib/supabase'

export default function ParentReportPage() {
  const { user } = useAuth()
  const [classrooms, setClassrooms] = useState([])
  const [selected, setSelected] = useState(null)
  const [students, setStudents] = useState([])
  const [assignments, setAssignments] = useState([])
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(false)

  useEffect(() => {
    if (!user) return
    supabase.from('classrooms').select('*').eq('teacher_id', user.id).then(({data})=>setClassrooms(data||[]))
  }, [user])

  const loadData = async (classroom) => {
    setSelected(classroom); setLoading(true)
    const [{ data: enrollments }, { data: hw }] = await Promise.all([
      supabase.from('student_enrollments').select('*, student:student_id(email)').eq('classroom_id', classroom.id),
      supabase.from('homework_assignments').select('*').eq('classroom_id', classroom.id).order('due_date')
    ])
    setStudents(enrollments||[]); setAssignments(hw||[]); setLoading(false)
  }

  const generateReport = (student) => {
    const open = assignments.filter(a=>a.status==='open').length
    const total = assignments.length
    const lines = [
      'FLASHFO STUDENT PROGRESS REPORT',
      '================================',
      'Student: ' + (student.student?.email || 'Student'),
      'Class: ' + selected?.name,
      'Generated: ' + new Date().toLocaleDateString(),
      '',
      'Assignments: ' + total + ' total, ' + (total-open) + ' completed, ' + open + ' open',
      '',
      ...assignments.map(a => '- ' + a.title + (a.due_date ? ' (due: ' + new Date(a.due_date).toLocaleDateString() + ')' : '') + ' [' + a.status + ']'),
      '', 'Generated by Flashfo — flashfo.org'
    ]
    const blob = new Blob([lines.join('\n')], { type:'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = 'flashfo-report.txt'; a.click(); URL.revokeObjectURL(url)
  }

  return (
    <div style={{ maxWidth:700, margin:'0 auto', padding:'0 16px 40px' }}>
      <h1 style={{ fontSize:22, fontWeight:700, color:'var(--c-t1)', margin:'0 0 4px' }}>Parent Reports</h1>
      <p style={{ color:'var(--c-t2)', fontSize:14, marginBottom:24 }}>Generate a progress report for any student.</p>
      {!selected ? (
        <div style={{ display:'grid', gap:10 }}>
          {classrooms.length === 0 && <p style={{ color:'var(--c-t3)', textAlign:'center', padding:32 }}>No classrooms yet.</p>}
          {classrooms.map(c=>(
            <div key={c.id} onClick={()=>loadData(c)} style={{ background:'var(--c-surface)', border:'1px solid var(--c-line)', borderRadius:10, padding:'14px 18px', cursor:'pointer', display:'flex', justifyContent:'space-between', alignItems:'center' }}>
              <div><p style={{ margin:'0 0 2px', fontWeight:600, color:'var(--c-t1)', fontSize:14 }}>{c.name}</p>{c.subject && <span style={{ fontSize:12, color:'var(--c-t3)' }}>{c.subject}</span>}</div>
              <span style={{ fontSize:12, color:'var(--c-t2)' }}>Select →</span>
            </div>
          ))}
        </div>
      ) : (
        <div>
          <button onClick={()=>setSelected(null)} style={{ background:'none', border:'none', color:'var(--c-t2)', cursor:'pointer', fontSize:13, marginBottom:16 }}>← All classes</button>
          <h2 style={{ fontSize:16, fontWeight:700, color:'var(--c-t1)', marginBottom:16 }}>{selected.name} — {students.length} students</h2>
          {loading && <p style={{ color:'var(--c-t3)', fontSize:13 }}>Loading...</p>}
          <div style={{ display:'flex', flexDirection:'column', gap:10 }}>
            {students.map(s=>(
              <div key={s.id} style={{ background:'var(--c-surface)', border:'1px solid var(--c-line)', borderRadius:10, padding:'14px 18px', display:'flex', justifyContent:'space-between', alignItems:'center' }}>
                <div><p style={{ margin:'0 0 2px', fontWeight:600, color:'var(--c-t1)', fontSize:14 }}>{s.student?.email?.split('@')[0]}</p><span style={{ fontSize:12, color:'var(--c-t3)' }}>{s.student?.email}</span></div>
                <button onClick={()=>generateReport(s)} style={{ padding:'7px 14px', borderRadius:8, background:'#2563eb', color:'#fff', border:'none', fontSize:12, fontWeight:600, cursor:'pointer' }}>⬇ Report</button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}