'use client'
import { useState } from 'react'
import { useAuth } from '@/lib/useAuth'
import { saveItem } from '@/lib/savedItems'
import { printContent } from '@/lib/exportPdf'
import UploadGenerate from '@/components/UploadGenerate'

function printPDF(title, text) {
  const win = window.open('','_blank')
  const safe = text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
  win.document.write('<html><head><title>'+title+'</title><style>body{font-family:system-ui,sans-serif;max-width:760px;margin:40px auto;color:#111;font-size:14px;line-height:1.7;white-space:pre-wrap}h1{font-size:22px;margin-bottom:4px}.sub{color:#666;font-size:12px;margin-bottom:28px}@media print{body{margin:20px}}</style></head><body><h1>'+title+'</h1><div class="sub">'+new Date().toLocaleDateString()+'</div><div>'+safe+'</div></body></html>')
  win.document.close(); win.focus(); setTimeout(()=>win.print(),400)
}
import UploadInput from '@/components/UploadInput'

function printContent(title, content) {
  const w = window.open('','_blank')
  w.document.write(`<!DOCTYPE html><html><head><title>${title}</title>
  <style>body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;color:#111;line-height:1.6}h1{font-size:20px;margin-bottom:4px}.sub{color:#666;font-size:13px;margin-bottom:24px}pre,p{font-size:14px;white-space:pre-wrap}@media print{body{margin:20px}}</style>
  </head><body><h1>${title}</h1><div class="sub">Generated by Flashfo</div><p>${content.replace(/\n/g,'<br>')}</p></body></html>`)
  w.document.close(); w.focus(); w.print()
}

export default function LessonBuilderPage() {
  const { user } = useAuth()
  const [inputText, setInputText] = useState('')
  const [form, setForm] = useState({ topic:'', grade:'', duration:'', objectives:'' })
  const [output, setOutput]   = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError]     = useState('')
  const [saving, setSaving]   = useState(false)
  const [saveFeedback, setSaveFeedback] = useState('')
  const set = (k,v) => setForm(f=>({...f,[k]:v}))

  async function generate() {
    const topic = form.topic.trim() || inputText.trim()
    if (!topic) return
    setLoading(true); setOutput(''); setError('')
    try {
      const topicText = [topic, form.grade&&'Grade/Level: '+form.grade, form.duration&&'Duration: '+form.duration, form.objectives&&'Objectives: '+form.objectives].filter(Boolean).join(' | ')
      const res = await fetch('/api/rpc',{method:'POST',headers:{'Content-Type':'application/json'},
        body:JSON.stringify({fn:'generateLessonPlanFromItems',args:[[{type:'topic',value:topicText}],form.grade||'General','English']})})
      const data = await res.json()
      if (data.error) setError(data.error)
      else setOutput(typeof data.result==='string'?data.result:JSON.stringify(data.result))
    } catch { setError('Something went wrong.') }
    finally { setLoading(false) }
  }

  async function doSave() {
    if (!user||!output) return
    setSaving(true)
    try {
      await saveItem(user.id,'lesson',form.topic||inputText.substring(0,60)||'Lesson Plan',{output,form})
      setSaveFeedback('✓ Saved!'); setTimeout(()=>setSaveFeedback(''),3000)
    } catch { setSaveFeedback('Save failed') }
    finally { setSaving(false) }
  }

  return (
    <div className="p-6 max-w-3xl mx-auto w-full">
      <h1 className="text-2xl font-bold text-t1 tracking-tight mb-1">Lesson Builder</h1>
      <p className="text-sm text-t2 mb-6">Build a complete lesson plan from a topic, notes, or uploaded material.</p>

      <div className="mb-3"><UploadGenerate onTextExtracted={t=>{setForm(f=>({...f,topic:t.substring(0,200)}))}} label="Fill from file or URL"/></div>
      <div className="bg-surface border border-line rounded-2xl p-5 space-y-4 mb-4">
        <UploadInput onText={t=>{setInputText(t);set('topic',t.substring(0,120))}} placeholder="Enter a topic (e.g. The Water Cycle, World War II)"/>
        {[{k:'grade',label:'Grade / Level',ph:'e.g. Grade 8, High School'},{k:'duration',label:'Duration',ph:'e.g. 45 minutes'},{k:'objectives',label:'Learning Objectives',ph:'Students will be able to...'}].map(({k,label,ph})=>(
          <div key={k}>
            <label className="block text-[11px] font-semibold text-t3 uppercase tracking-wider mb-1.5">{label} <span className="text-t3 font-normal normal-case">(optional)</span></label>
            {k==='objectives'
              ? <textarea value={form[k]} onChange={e=>set(k,e.target.value)} placeholder={ph} rows={2}
                  className="w-full bg-surface2 border border-line rounded-lg px-3 py-2 text-sm text-t1 outline-none focus:border-blue-400 resize-none placeholder:text-t3"/>
              : <input value={form[k]} onChange={e=>set(k,e.target.value)} placeholder={ph}
                  className="w-full h-9 bg-surface2 border border-line rounded-lg px-3 text-sm text-t1 outline-none focus:border-blue-400 placeholder:text-t3"/>}
          </div>
        ))}
      </div>

      <button onClick={generate} disabled={loading||(!form.topic.trim()&&!inputText.trim())}
        className="h-9 px-5 bg-blue-700 text-white text-sm font-semibold rounded-xl hover:bg-blue-800 disabled:opacity-40 flex items-center gap-2 mb-4">
        {loading?<><span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"/>Building...</>:'Generate Lesson Plan'}
      </button>

      {error&&<div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl text-sm text-red-500 mb-4">{error}</div>}
      {output&&(
        <div className="bg-surface border border-line rounded-2xl p-5">
          <div className="flex flex-wrap justify-between items-center mb-4 gap-2">
            <span className="text-[13px] font-bold text-t1">Lesson Plan</span>
            <div className="flex gap-2 items-center flex-wrap">
              {saveFeedback&&<span className="text-[11px] text-emerald-500">{saveFeedback}</span>}
              {user&&<button onClick={doSave} disabled={saving} className="h-7 px-3 bg-emerald-600 text-white text-[11px] font-semibold rounded-lg hover:bg-emerald-700 disabled:opacity-40">{saving?'Saving...':'💾 Save'}</button>}
              <button onClick={()=>printContent('Lesson Plan — '+(form.topic||'Untitled'),output)}
                className="h-7 px-3 bg-surface border border-line text-t2 text-[11px] rounded-lg hover:bg-surface2 flex items-center gap-1">
                <svg width="11" height="11" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M4 6V2h8v4M4 11H2V6h12v5h-2M4 9h8v5H4V9z"/></svg>Print / PDF
              </button>
              <button onClick={()=>navigator.clipboard.writeText(output)} className="h-7 px-3 text-[11px] text-blue-500 hover:underline">Copy</button>
            </div>
          </div>
          <div className="text-sm text-t1 leading-relaxed whitespace-pre-wrap">{output}</div>
        </div>
      )}
    </div>
  )
}
