'use client'
import { useEffect } from 'react'

export default function GlobalError({ error, reset }) {
  useEffect(() => {
      console.error('[Flashfo error]', error)
        }, [error])

          return (
              <div style={{
                    minHeight: '100vh',
                          background: '#0d1117',
                                display: 'flex',
                                      alignItems: 'center',
                                            justifyContent: 'center',
                                                  fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
                                                        padding: '24px',
                                                            }}>
                                                                  <div style={{ textAlign: 'center', maxWidth: 440 }}>
                                                                          <div style={{
                                                                                    width: 56, height: 56, borderRadius: 14,
                                                                                              background: 'linear-gradient(135deg, #1d4ed8, #4f46e5)',
                                                                                                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                                                                                                                  margin: '0 auto 24px',
                                                                                                                            boxShadow: '0 0 32px rgba(99,102,241,0.3)',
                                                                                                                                    }}>
                                                                                                                                              <svg width="24" height="24" viewBox="0 0 32 32" fill="none">
                                                                                                                                                          <polygon points="16,4 7,18 16,18 14,28 25,14 16,14" fill="white"/>
                                                                                                                                                                    </svg>
                                                                                                                                                                            </div>
                                                                                                                                                                                    <h1 style={{ fontSize: 20, fontWeight: 700, color: '#e6edf3', marginBottom: 8 }}>
                                                                                                                                                                                              Something went wrong
                                                                                                                                                                                                      </h1>
                                                                                                                                                                                                              <p style={{ fontSize: 14, color: '#8b949e', lineHeight: 1.6, marginBottom: 28 }}>
                                                                                                                                                                                                                        An unexpected error occurred. Try refreshing the page or going back.
                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                        <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                              onClick={reset}
                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                        padding: '10px 24px', borderRadius: 10,
                                                                                                                                                                                                                                                                                                      background: '#2563eb', color: '#fff',
                                                                                                                                                                                                                                                                                                                    border: 'none', fontWeight: 600, fontSize: 14,
                                                                                                                                                                                                                                                                                                                                  cursor: 'pointer', fontFamily: 'inherit',
                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                    Try again
                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                    href="/dashboard"
                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                              padding: '10px 24px', borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                            background: 'rgba(255,255,255,0.06)', color: '#8b949e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: '1px solid rgba(255,255,255,0.1)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: 600, fontSize: 14, textDecoration: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      display: 'inline-block',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Go to dashboard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
