'use client'
import { useState } from 'react'
import { useAuth } from '@/lib/useAuth'
import { saveItem } from '@/lib/savedItems'

function printPDF(title, text) {
  const win = window.open('','_blank')
  const safe = text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
  win.document.write('<html><head><title>'+title+'</title><style>body{font-family:system-ui,sans-serif;max-width:760px;margin:40px auto;color:#111;font-size:14px;line-height:1.7;white-space:pre-wrap}h1{font-size:22px;margin-bottom:4px}.sub{color:#666;font-size:12px;margin-bottom:28px}@media print{body{margin:20px}}</style></head><body><h1>'+title+'</h1><div class="sub">'+new Date().toLocaleDateString()+'</div><div>'+safe+'</div></body></html>')
  win.document.close(); win.focus(); setTimeout(()=>win.print(),400)
}
import UploadInput from '@/components/UploadInput'

function printContent(title, content) {
  const w = window.open('','_blank')
  w.document.write(`<!DOCTYPE html><html><head><title>${title}</title>
  <style>body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;color:#111;line-height:1.6}h1{font-size:20px;margin-bottom:4px}.sub{color:#666;font-size:13px;margin-bottom:24px}p{font-size:14px;white-space:pre-wrap}@media print{body{margin:20px}}</style>
  </head><body><h1>${title}</h1><div class="sub">Generated by Flashfo</div><p>${content.replace(/\n/g,'<br>')}</p></body></html>`)
  w.document.close(); w.focus(); w.print()
}

export default function SummarizePage() {
  const { user } = useAuth()
  const [inputText, setInputText] = useState('')
  const [output, setOutput] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError]   = useState('')
  const [saving, setSaving] = useState(false)
  const [saveFeedback, setSaveFeedback] = useState('')

  async function run() {
    if (!inputText.trim()) return
    setLoading(true); setOutput(''); setError('')
    try {
      const res = await fetch('/api/rpc',{method:'POST',headers:{'Content-Type':'application/json'},
        body:JSON.stringify({fn:'summarizeText',args:[inputText.trim(),'paragraph',300,'English']})})
      const data = await res.json()
      if (data.error) setError(data.error)
      else setOutput(typeof data.result==='string'?data.result:JSON.stringify(data.result))
    } catch { setError('Something went wrong.') }
    finally { setLoading(false) }
  }

  async function doSave() {
    if (!user||!output) return
    setSaving(true)
    try {
      await saveItem(user.id,'summary',inputText.substring(0,60)+'...',{output,input:inputText})
      setSaveFeedback('✓ Saved!'); setTimeout(()=>setSaveFeedback(''),3000)
    } catch { setSaveFeedback('Save failed') }
    finally { setSaving(false) }
  }

  return (
    <div className="p-6 max-w-3xl mx-auto w-full">
      <h1 className="text-2xl font-bold text-t1 tracking-tight mb-1">Summarize</h1>
      <p className="text-sm text-t2 mb-6">Paste text, upload a file, or enter a URL to get a clean summary.</p>
      <div className="bg-surface border border-line rounded-2xl p-5 mb-4">
        <UploadInput onText={t=>setInputText(t)} placeholder="Paste text, article content, or notes here..."/>
      </div>
      <button onClick={run} disabled={loading||!inputText.trim()}
        className="h-9 px-5 bg-blue-700 text-white text-sm font-semibold rounded-xl hover:bg-blue-800 disabled:opacity-40 flex items-center gap-2 mb-4">
        {loading?<><span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"/>Summarizing...</>:'Summarize'}
      </button>
      {error&&<div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl text-sm text-red-500 mb-4">{error}</div>}
      {output&&(
        <div className="bg-surface border border-line rounded-2xl p-5">
          <div className="flex flex-wrap justify-between items-center mb-3 gap-2">
            <span className="text-[13px] font-bold text-t1">Summary</span>
            <div className="flex gap-2 items-center flex-wrap">
              {saveFeedback&&<span className="text-[11px] text-emerald-500">{saveFeedback}</span>}
              {user&&<button onClick={doSave} disabled={saving} className="h-7 px-3 bg-emerald-600 text-white text-[11px] font-semibold rounded-lg hover:bg-emerald-700 disabled:opacity-40">{saving?'Saving...':'💾 Save'}</button>}
              <button onClick={()=>navigator.clipboard.writeText(output)} className="h-7 px-3 text-[11px] text-blue-500 hover:underline">Copy</button>
            </div>
          </div>
          <p className="text-sm text-t1 leading-relaxed whitespace-pre-wrap">{output}</p>
        </div>
      )}
    </div>
  )
}
